worker = 20
chunk_size = 50

# number of requested fake rows
rows = 1000_000

# three random level: 1,2,3
# level 1: Uses math/rand(Pseudo) with mutex locking
# level 2: Uses math/rand(Pseudo) with NO mutext locking, More performant but not goroutine safe.
# level 3: Uses crypto/rand(cryptographically secure) with mutext locking
random_level = 1

# save data
[database.destination]
type = "mysql"
dsn = "user:password@tcp(127.0.0.1:3306)/school"
pre_queries = [
"""
CREATE TABLE IF NOT EXISTS students (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    gender ENUM('male', 'female', 'other'),
    code INT,
    dob DATE,
    address TEXT,
    created_at DATETIME,
    PRIMARY KEY (id)
);
"""
]

# all values should be between quotation,
[query]
insert_clause = "INSERT IGNORE INTO students(name, gender, code, dob, address, created_at) VALUES"
values_clause = """
(
'__FIRST_NAME__ __LAST_NAME__',
'__RANDOM_STRING(male,female,other)__',
'__NUMBER(100,999)__',
'__DATE_RANGE(2000-01-01 00:00:00,2010-01-01 00:00:00)__',
'__CITY__ __ZIP__, __STREET_NAME__ __STREET_NUMBER__',
'__DATE__'
)
"""


