# two file after running will be generated, logs and summary. out_errors_fake_students_220709235010.log & out_summary_fake_students_220709235010.txt
process_name = "fake_students"
worker = 10
chunk_size2 = 2_000

# number of requested fake rows
rows = 1_000_000

[database]
type = "mysql"
dsn = "user:password@tcp(127.0.0.1:3306)/school"

[query]
insert_clause = "INSERT INTO students(name, gender, code, dob, address, created_at)"
values_clause = """
VALUES(
'__PERSON_FIRST_NAME__ __PERSON_LAST_NAME__',
'__ENUM(male,female,other)__',
'__INT(100,999)__',
'__DATE(1950-01-01,2010-01-01)__',
'__ADDRESS__',
'__DATETIME(2020-01-01 00:00:00,2022-07-10 23:59:59)__')
"""


