# two file after running will be generated, logs and summary. out_errors_fake_students_220709235010.log & out_summary_fake_students_220709235010.txt
process_name = "fake_students"
worker = 10
chunk_size2 = 2_000

# number of requested fake rows
#rows = 1_000_000
rows = 10000


# source database for getting ids in case we have foreign keys
[database.source]
type = "mysql"
dsn = "user:password@tcp(127.0.0.1:3306)/school"

# save data
[database.destination]
type = "mysql"
dsn = "user:password@tcp(127.0.0.1:3306)/school"
pre_queries = [
"""
CREATE TABLE IF NOT EXIST students (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    gender ENUM('male', 'female', 'other'),
    code INT,
    dob DATE,
    address TEXT,
    created_at DATETIME,
    PRIMARY KEY (id)
);
"""
]

# all values should be between quotation,
[query]
insert_clause = "INSERT INTO students(name, gender, code, dob, address, created_at)"
values_clause = """
VALUES(
'__FIRST_NAME__ __LAST_NAME__',
'__RANDOM_STRING(male,female,other)__',
'__NUMBER(100,999)__',
'__DATE_RANGE(2000-01-01 00:00:00,2010-01-01 00:00:00)__',
'__CITY__ __ZIP__, __STREET_NAME__ __STREET_NUMBER__',
'__DATE__')
"""


